package com.graymatter.service;

import java.io.OutputStream;
import java.time.LocalDateTime;

import org.springframework.stereotype.Service;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

@Service
public class DegreeReportService extends ReportService {

	public Document generateReport(Degree degree, OutputStream outputStream) throws DocumentException {
		Document document = new Document();
		PdfWriter.getInstance(document, outputStream);
		document.open();
		addMetaData(document, degree);
		addPageBody(document, degree);
		document.close();
		return document;
	}

	public void addMetaData(Document document, Degree degree) {
		document.addTitle("Report - " + degree.getName());
		document.addAuthor("Jeewa Education");
		document.addCreator("Jeewa Education");
	}

	public void addPageBody(Document document, Degree degree) throws DocumentException {
		Paragraph para = new Paragraph();
		// one empty line
		addEmptyLine(para, 1);
		// add title
		Paragraph titlePara = new Paragraph("Degree Report - " + degree.getName(), CAT_FONT);
		titlePara.setAlignment(Element.ALIGN_CENTER);
		para.add(titlePara);

		addEmptyLine(para, 1);

		para.add(
				new Paragraph("Degree report generated by Jeewa Education at " + LocalDateTime.now(), SMALL_BOLD_FONT));
		// add university details
		addUniversity(para, degree.getUniversity());

		// add degree details
		addDegree(para, degree);

		document.add(para);
	}

	private void addDegree(Paragraph para, Degree degree) {
		addEmptyLine(para, 3);

		para.add(new Paragraph("Degree Program Details: ", SUB_FONT));
		addEmptyLine(para, 1);
		para.add(new Paragraph("ID: " + degree.getId(), SMALL_BOLD_FONT));
		addEmptyLine(para, 1);
		para.add(new Paragraph("Name: " + degree.getName(), SMALL_BOLD_FONT));
		addEmptyLine(para, 1);
		para.add(new Paragraph("Duration: " + degree.getDuration() + " Years", SMALL_BOLD_FONT));
		addEmptyLine(para, 1);
		para.add(new Paragraph("Fee: " + degree.getFee(), SMALL_BOLD_FONT));
		addEmptyLine(para, 1);
		para.add(new Paragraph("Description: " + degree.getDescription(), SMALL_BOLD_FONT));
	}
}
